// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/sut63/team05/ent/groupofage"
	"github.com/sut63/team05/ent/predicate"
)

// GroupOfAgeDelete is the builder for deleting a GroupOfAge entity.
type GroupOfAgeDelete struct {
	config
	hooks      []Hook
	mutation   *GroupOfAgeMutation
	predicates []predicate.GroupOfAge
}

// Where adds a new predicate to the delete builder.
func (goad *GroupOfAgeDelete) Where(ps ...predicate.GroupOfAge) *GroupOfAgeDelete {
	goad.predicates = append(goad.predicates, ps...)
	return goad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (goad *GroupOfAgeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(goad.hooks) == 0 {
		affected, err = goad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroupOfAgeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			goad.mutation = mutation
			affected, err = goad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(goad.hooks) - 1; i >= 0; i-- {
			mut = goad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, goad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (goad *GroupOfAgeDelete) ExecX(ctx context.Context) int {
	n, err := goad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (goad *GroupOfAgeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: groupofage.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: groupofage.FieldID,
			},
		},
	}
	if ps := goad.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, goad.driver, _spec)
}

// GroupOfAgeDeleteOne is the builder for deleting a single GroupOfAge entity.
type GroupOfAgeDeleteOne struct {
	goad *GroupOfAgeDelete
}

// Exec executes the deletion query.
func (goado *GroupOfAgeDeleteOne) Exec(ctx context.Context) error {
	n, err := goado.goad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{groupofage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (goado *GroupOfAgeDeleteOne) ExecX(ctx context.Context) {
	goado.goad.ExecX(ctx)
}
