// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/sut63/team05/ent/groupofage"
	"github.com/sut63/team05/ent/predicate"
	"github.com/sut63/team05/ent/product"
)

// GroupOfAgeQuery is the builder for querying GroupOfAge entities.
type GroupOfAgeQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.GroupOfAge
	// eager-loading edges.
	withGroupageProduct *ProductQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (goaq *GroupOfAgeQuery) Where(ps ...predicate.GroupOfAge) *GroupOfAgeQuery {
	goaq.predicates = append(goaq.predicates, ps...)
	return goaq
}

// Limit adds a limit step to the query.
func (goaq *GroupOfAgeQuery) Limit(limit int) *GroupOfAgeQuery {
	goaq.limit = &limit
	return goaq
}

// Offset adds an offset step to the query.
func (goaq *GroupOfAgeQuery) Offset(offset int) *GroupOfAgeQuery {
	goaq.offset = &offset
	return goaq
}

// Order adds an order step to the query.
func (goaq *GroupOfAgeQuery) Order(o ...OrderFunc) *GroupOfAgeQuery {
	goaq.order = append(goaq.order, o...)
	return goaq
}

// QueryGroupageProduct chains the current query on the groupage_product edge.
func (goaq *GroupOfAgeQuery) QueryGroupageProduct() *ProductQuery {
	query := &ProductQuery{config: goaq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := goaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupofage.Table, groupofage.FieldID, goaq.sqlQuery()),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, groupofage.GroupageProductTable, groupofage.GroupageProductColumn),
		)
		fromU = sqlgraph.SetNeighbors(goaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GroupOfAge entity in the query. Returns *NotFoundError when no groupofage was found.
func (goaq *GroupOfAgeQuery) First(ctx context.Context) (*GroupOfAge, error) {
	goas, err := goaq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(goas) == 0 {
		return nil, &NotFoundError{groupofage.Label}
	}
	return goas[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (goaq *GroupOfAgeQuery) FirstX(ctx context.Context) *GroupOfAge {
	goa, err := goaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return goa
}

// FirstID returns the first GroupOfAge id in the query. Returns *NotFoundError when no id was found.
func (goaq *GroupOfAgeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = goaq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{groupofage.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (goaq *GroupOfAgeQuery) FirstXID(ctx context.Context) int {
	id, err := goaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only GroupOfAge entity in the query, returns an error if not exactly one entity was returned.
func (goaq *GroupOfAgeQuery) Only(ctx context.Context) (*GroupOfAge, error) {
	goas, err := goaq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(goas) {
	case 1:
		return goas[0], nil
	case 0:
		return nil, &NotFoundError{groupofage.Label}
	default:
		return nil, &NotSingularError{groupofage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (goaq *GroupOfAgeQuery) OnlyX(ctx context.Context) *GroupOfAge {
	goa, err := goaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return goa
}

// OnlyID returns the only GroupOfAge id in the query, returns an error if not exactly one id was returned.
func (goaq *GroupOfAgeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = goaq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{groupofage.Label}
	default:
		err = &NotSingularError{groupofage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (goaq *GroupOfAgeQuery) OnlyIDX(ctx context.Context) int {
	id, err := goaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GroupOfAges.
func (goaq *GroupOfAgeQuery) All(ctx context.Context) ([]*GroupOfAge, error) {
	if err := goaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return goaq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (goaq *GroupOfAgeQuery) AllX(ctx context.Context) []*GroupOfAge {
	goas, err := goaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return goas
}

// IDs executes the query and returns a list of GroupOfAge ids.
func (goaq *GroupOfAgeQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := goaq.Select(groupofage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (goaq *GroupOfAgeQuery) IDsX(ctx context.Context) []int {
	ids, err := goaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (goaq *GroupOfAgeQuery) Count(ctx context.Context) (int, error) {
	if err := goaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return goaq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (goaq *GroupOfAgeQuery) CountX(ctx context.Context) int {
	count, err := goaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (goaq *GroupOfAgeQuery) Exist(ctx context.Context) (bool, error) {
	if err := goaq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return goaq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (goaq *GroupOfAgeQuery) ExistX(ctx context.Context) bool {
	exist, err := goaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (goaq *GroupOfAgeQuery) Clone() *GroupOfAgeQuery {
	return &GroupOfAgeQuery{
		config:     goaq.config,
		limit:      goaq.limit,
		offset:     goaq.offset,
		order:      append([]OrderFunc{}, goaq.order...),
		unique:     append([]string{}, goaq.unique...),
		predicates: append([]predicate.GroupOfAge{}, goaq.predicates...),
		// clone intermediate query.
		sql:  goaq.sql.Clone(),
		path: goaq.path,
	}
}

//  WithGroupageProduct tells the query-builder to eager-loads the nodes that are connected to
// the "groupage_product" edge. The optional arguments used to configure the query builder of the edge.
func (goaq *GroupOfAgeQuery) WithGroupageProduct(opts ...func(*ProductQuery)) *GroupOfAgeQuery {
	query := &ProductQuery{config: goaq.config}
	for _, opt := range opts {
		opt(query)
	}
	goaq.withGroupageProduct = query
	return goaq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GroupOfAgeName string `json:"group_of_age_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GroupOfAge.Query().
//		GroupBy(groupofage.FieldGroupOfAgeName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (goaq *GroupOfAgeQuery) GroupBy(field string, fields ...string) *GroupOfAgeGroupBy {
	group := &GroupOfAgeGroupBy{config: goaq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := goaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return goaq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		GroupOfAgeName string `json:"group_of_age_name,omitempty"`
//	}
//
//	client.GroupOfAge.Query().
//		Select(groupofage.FieldGroupOfAgeName).
//		Scan(ctx, &v)
//
func (goaq *GroupOfAgeQuery) Select(field string, fields ...string) *GroupOfAgeSelect {
	selector := &GroupOfAgeSelect{config: goaq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := goaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return goaq.sqlQuery(), nil
	}
	return selector
}

func (goaq *GroupOfAgeQuery) prepareQuery(ctx context.Context) error {
	if goaq.path != nil {
		prev, err := goaq.path(ctx)
		if err != nil {
			return err
		}
		goaq.sql = prev
	}
	return nil
}

func (goaq *GroupOfAgeQuery) sqlAll(ctx context.Context) ([]*GroupOfAge, error) {
	var (
		nodes       = []*GroupOfAge{}
		_spec       = goaq.querySpec()
		loadedTypes = [1]bool{
			goaq.withGroupageProduct != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &GroupOfAge{config: goaq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, goaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := goaq.withGroupageProduct; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*GroupOfAge)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
		}
		query.withFKs = true
		query.Where(predicate.Product(func(s *sql.Selector) {
			s.Where(sql.InValues(groupofage.GroupageProductColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.group_of_age_id
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "group_of_age_id" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "group_of_age_id" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.GroupageProduct = append(node.Edges.GroupageProduct, n)
		}
	}

	return nodes, nil
}

func (goaq *GroupOfAgeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := goaq.querySpec()
	return sqlgraph.CountNodes(ctx, goaq.driver, _spec)
}

func (goaq *GroupOfAgeQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := goaq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (goaq *GroupOfAgeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   groupofage.Table,
			Columns: groupofage.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: groupofage.FieldID,
			},
		},
		From:   goaq.sql,
		Unique: true,
	}
	if ps := goaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := goaq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := goaq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := goaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (goaq *GroupOfAgeQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(goaq.driver.Dialect())
	t1 := builder.Table(groupofage.Table)
	selector := builder.Select(t1.Columns(groupofage.Columns...)...).From(t1)
	if goaq.sql != nil {
		selector = goaq.sql
		selector.Select(selector.Columns(groupofage.Columns...)...)
	}
	for _, p := range goaq.predicates {
		p(selector)
	}
	for _, p := range goaq.order {
		p(selector)
	}
	if offset := goaq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := goaq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GroupOfAgeGroupBy is the builder for group-by GroupOfAge entities.
type GroupOfAgeGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (goagb *GroupOfAgeGroupBy) Aggregate(fns ...AggregateFunc) *GroupOfAgeGroupBy {
	goagb.fns = append(goagb.fns, fns...)
	return goagb
}

// Scan applies the group-by query and scan the result into the given value.
func (goagb *GroupOfAgeGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := goagb.path(ctx)
	if err != nil {
		return err
	}
	goagb.sql = query
	return goagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (goagb *GroupOfAgeGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := goagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (goagb *GroupOfAgeGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(goagb.fields) > 1 {
		return nil, errors.New("ent: GroupOfAgeGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := goagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (goagb *GroupOfAgeGroupBy) StringsX(ctx context.Context) []string {
	v, err := goagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (goagb *GroupOfAgeGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = goagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupofage.Label}
	default:
		err = fmt.Errorf("ent: GroupOfAgeGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (goagb *GroupOfAgeGroupBy) StringX(ctx context.Context) string {
	v, err := goagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (goagb *GroupOfAgeGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(goagb.fields) > 1 {
		return nil, errors.New("ent: GroupOfAgeGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := goagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (goagb *GroupOfAgeGroupBy) IntsX(ctx context.Context) []int {
	v, err := goagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (goagb *GroupOfAgeGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = goagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupofage.Label}
	default:
		err = fmt.Errorf("ent: GroupOfAgeGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (goagb *GroupOfAgeGroupBy) IntX(ctx context.Context) int {
	v, err := goagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (goagb *GroupOfAgeGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(goagb.fields) > 1 {
		return nil, errors.New("ent: GroupOfAgeGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := goagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (goagb *GroupOfAgeGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := goagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (goagb *GroupOfAgeGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = goagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupofage.Label}
	default:
		err = fmt.Errorf("ent: GroupOfAgeGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (goagb *GroupOfAgeGroupBy) Float64X(ctx context.Context) float64 {
	v, err := goagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (goagb *GroupOfAgeGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(goagb.fields) > 1 {
		return nil, errors.New("ent: GroupOfAgeGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := goagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (goagb *GroupOfAgeGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := goagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (goagb *GroupOfAgeGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = goagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupofage.Label}
	default:
		err = fmt.Errorf("ent: GroupOfAgeGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (goagb *GroupOfAgeGroupBy) BoolX(ctx context.Context) bool {
	v, err := goagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (goagb *GroupOfAgeGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := goagb.sqlQuery().Query()
	if err := goagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (goagb *GroupOfAgeGroupBy) sqlQuery() *sql.Selector {
	selector := goagb.sql
	columns := make([]string, 0, len(goagb.fields)+len(goagb.fns))
	columns = append(columns, goagb.fields...)
	for _, fn := range goagb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(goagb.fields...)
}

// GroupOfAgeSelect is the builder for select fields of GroupOfAge entities.
type GroupOfAgeSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (goas *GroupOfAgeSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := goas.path(ctx)
	if err != nil {
		return err
	}
	goas.sql = query
	return goas.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (goas *GroupOfAgeSelect) ScanX(ctx context.Context, v interface{}) {
	if err := goas.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (goas *GroupOfAgeSelect) Strings(ctx context.Context) ([]string, error) {
	if len(goas.fields) > 1 {
		return nil, errors.New("ent: GroupOfAgeSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := goas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (goas *GroupOfAgeSelect) StringsX(ctx context.Context) []string {
	v, err := goas.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (goas *GroupOfAgeSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = goas.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupofage.Label}
	default:
		err = fmt.Errorf("ent: GroupOfAgeSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (goas *GroupOfAgeSelect) StringX(ctx context.Context) string {
	v, err := goas.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (goas *GroupOfAgeSelect) Ints(ctx context.Context) ([]int, error) {
	if len(goas.fields) > 1 {
		return nil, errors.New("ent: GroupOfAgeSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := goas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (goas *GroupOfAgeSelect) IntsX(ctx context.Context) []int {
	v, err := goas.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (goas *GroupOfAgeSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = goas.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupofage.Label}
	default:
		err = fmt.Errorf("ent: GroupOfAgeSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (goas *GroupOfAgeSelect) IntX(ctx context.Context) int {
	v, err := goas.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (goas *GroupOfAgeSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(goas.fields) > 1 {
		return nil, errors.New("ent: GroupOfAgeSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := goas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (goas *GroupOfAgeSelect) Float64sX(ctx context.Context) []float64 {
	v, err := goas.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (goas *GroupOfAgeSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = goas.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupofage.Label}
	default:
		err = fmt.Errorf("ent: GroupOfAgeSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (goas *GroupOfAgeSelect) Float64X(ctx context.Context) float64 {
	v, err := goas.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (goas *GroupOfAgeSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(goas.fields) > 1 {
		return nil, errors.New("ent: GroupOfAgeSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := goas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (goas *GroupOfAgeSelect) BoolsX(ctx context.Context) []bool {
	v, err := goas.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (goas *GroupOfAgeSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = goas.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{groupofage.Label}
	default:
		err = fmt.Errorf("ent: GroupOfAgeSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (goas *GroupOfAgeSelect) BoolX(ctx context.Context) bool {
	v, err := goas.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (goas *GroupOfAgeSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := goas.sqlQuery().Query()
	if err := goas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (goas *GroupOfAgeSelect) sqlQuery() sql.Querier {
	selector := goas.sql
	selector.Select(selector.Columns(goas.fields...)...)
	return selector
}
