// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/sut63/team05/ent/hospital"
	"github.com/sut63/team05/ent/insurance"
	"github.com/sut63/team05/ent/recordinsurance"
)

// HospitalCreate is the builder for creating a Hospital entity.
type HospitalCreate struct {
	config
	mutation *HospitalMutation
	hooks    []Hook
}

// SetHospitalName sets the hospital_name field.
func (hc *HospitalCreate) SetHospitalName(s string) *HospitalCreate {
	hc.mutation.SetHospitalName(s)
	return hc
}

// AddHospitalInsuranceIDs adds the hospital_insurance edge to Insurance by ids.
func (hc *HospitalCreate) AddHospitalInsuranceIDs(ids ...int) *HospitalCreate {
	hc.mutation.AddHospitalInsuranceIDs(ids...)
	return hc
}

// AddHospitalInsurance adds the hospital_insurance edges to Insurance.
func (hc *HospitalCreate) AddHospitalInsurance(i ...*Insurance) *HospitalCreate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return hc.AddHospitalInsuranceIDs(ids...)
}

// AddHospitalRecordinsuranceIDs adds the hospital_recordinsurance edge to Recordinsurance by ids.
func (hc *HospitalCreate) AddHospitalRecordinsuranceIDs(ids ...int) *HospitalCreate {
	hc.mutation.AddHospitalRecordinsuranceIDs(ids...)
	return hc
}

// AddHospitalRecordinsurance adds the hospital_recordinsurance edges to Recordinsurance.
func (hc *HospitalCreate) AddHospitalRecordinsurance(r ...*Recordinsurance) *HospitalCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return hc.AddHospitalRecordinsuranceIDs(ids...)
}

// Mutation returns the HospitalMutation object of the builder.
func (hc *HospitalCreate) Mutation() *HospitalMutation {
	return hc.mutation
}

// Save creates the Hospital in the database.
func (hc *HospitalCreate) Save(ctx context.Context) (*Hospital, error) {
	if _, ok := hc.mutation.HospitalName(); !ok {
		return nil, &ValidationError{Name: "hospital_name", err: errors.New("ent: missing required field \"hospital_name\"")}
	}
	if v, ok := hc.mutation.HospitalName(); ok {
		if err := hospital.HospitalNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "hospital_name", err: fmt.Errorf("ent: validator failed for field \"hospital_name\": %w", err)}
		}
	}
	var (
		err  error
		node *Hospital
	)
	if len(hc.hooks) == 0 {
		node, err = hc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HospitalMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			hc.mutation = mutation
			node, err = hc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(hc.hooks) - 1; i >= 0; i-- {
			mut = hc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, hc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HospitalCreate) SaveX(ctx context.Context) *Hospital {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (hc *HospitalCreate) sqlSave(ctx context.Context) (*Hospital, error) {
	h, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	h.ID = int(id)
	return h, nil
}

func (hc *HospitalCreate) createSpec() (*Hospital, *sqlgraph.CreateSpec) {
	var (
		h     = &Hospital{config: hc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: hospital.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: hospital.FieldID,
			},
		}
	)
	if value, ok := hc.mutation.HospitalName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: hospital.FieldHospitalName,
		})
		h.HospitalName = value
	}
	if nodes := hc.mutation.HospitalInsuranceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hospital.HospitalInsuranceTable,
			Columns: []string{hospital.HospitalInsuranceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: insurance.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := hc.mutation.HospitalRecordinsuranceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   hospital.HospitalRecordinsuranceTable,
			Columns: []string{hospital.HospitalRecordinsuranceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: recordinsurance.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return h, _spec
}
