// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/sut63/team05/ent/moneytransfer"
	"github.com/sut63/team05/ent/predicate"
)

// MoneyTransferDelete is the builder for deleting a MoneyTransfer entity.
type MoneyTransferDelete struct {
	config
	hooks      []Hook
	mutation   *MoneyTransferMutation
	predicates []predicate.MoneyTransfer
}

// Where adds a new predicate to the delete builder.
func (mtd *MoneyTransferDelete) Where(ps ...predicate.MoneyTransfer) *MoneyTransferDelete {
	mtd.predicates = append(mtd.predicates, ps...)
	return mtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mtd *MoneyTransferDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mtd.hooks) == 0 {
		affected, err = mtd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MoneyTransferMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mtd.mutation = mutation
			affected, err = mtd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mtd.hooks) - 1; i >= 0; i-- {
			mut = mtd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mtd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtd *MoneyTransferDelete) ExecX(ctx context.Context) int {
	n, err := mtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mtd *MoneyTransferDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: moneytransfer.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: moneytransfer.FieldID,
			},
		},
	}
	if ps := mtd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mtd.driver, _spec)
}

// MoneyTransferDeleteOne is the builder for deleting a single MoneyTransfer entity.
type MoneyTransferDeleteOne struct {
	mtd *MoneyTransferDelete
}

// Exec executes the deletion query.
func (mtdo *MoneyTransferDeleteOne) Exec(ctx context.Context) error {
	n, err := mtdo.mtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{moneytransfer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mtdo *MoneyTransferDeleteOne) ExecX(ctx context.Context) {
	mtdo.mtd.ExecX(ctx)
}
