// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/sut63/team05/ent/gender"
	"github.com/sut63/team05/ent/groupofage"
	"github.com/sut63/team05/ent/insurance"
	"github.com/sut63/team05/ent/officer"
	"github.com/sut63/team05/ent/product"
)

// ProductCreate is the builder for creating a Product entity.
type ProductCreate struct {
	config
	mutation *ProductMutation
	hooks    []Hook
}

// SetProductName sets the product_name field.
func (pc *ProductCreate) SetProductName(s string) *ProductCreate {
	pc.mutation.SetProductName(s)
	return pc
}

// SetProductPrice sets the product_price field.
func (pc *ProductCreate) SetProductPrice(i int) *ProductCreate {
	pc.mutation.SetProductPrice(i)
	return pc
}

// SetProductTime sets the product_time field.
func (pc *ProductCreate) SetProductTime(i int) *ProductCreate {
	pc.mutation.SetProductTime(i)
	return pc
}

// SetProductPaymentOfYear sets the product_payment_of_year field.
func (pc *ProductCreate) SetProductPaymentOfYear(f float64) *ProductCreate {
	pc.mutation.SetProductPaymentOfYear(f)
	return pc
}

// SetGenderID sets the Gender edge to Gender by id.
func (pc *ProductCreate) SetGenderID(id int) *ProductCreate {
	pc.mutation.SetGenderID(id)
	return pc
}

// SetNillableGenderID sets the Gender edge to Gender by id if the given value is not nil.
func (pc *ProductCreate) SetNillableGenderID(id *int) *ProductCreate {
	if id != nil {
		pc = pc.SetGenderID(*id)
	}
	return pc
}

// SetGender sets the Gender edge to Gender.
func (pc *ProductCreate) SetGender(g *Gender) *ProductCreate {
	return pc.SetGenderID(g.ID)
}

// SetGoupOfAgeID sets the Goup_Of_Age edge to GroupOfAge by id.
func (pc *ProductCreate) SetGoupOfAgeID(id int) *ProductCreate {
	pc.mutation.SetGoupOfAgeID(id)
	return pc
}

// SetNillableGoupOfAgeID sets the Goup_Of_Age edge to GroupOfAge by id if the given value is not nil.
func (pc *ProductCreate) SetNillableGoupOfAgeID(id *int) *ProductCreate {
	if id != nil {
		pc = pc.SetGoupOfAgeID(*id)
	}
	return pc
}

// SetGoupOfAge sets the Goup_Of_Age edge to GroupOfAge.
func (pc *ProductCreate) SetGoupOfAge(g *GroupOfAge) *ProductCreate {
	return pc.SetGoupOfAgeID(g.ID)
}

// SetOfficerID sets the Officer edge to Officer by id.
func (pc *ProductCreate) SetOfficerID(id int) *ProductCreate {
	pc.mutation.SetOfficerID(id)
	return pc
}

// SetNillableOfficerID sets the Officer edge to Officer by id if the given value is not nil.
func (pc *ProductCreate) SetNillableOfficerID(id *int) *ProductCreate {
	if id != nil {
		pc = pc.SetOfficerID(*id)
	}
	return pc
}

// SetOfficer sets the Officer edge to Officer.
func (pc *ProductCreate) SetOfficer(o *Officer) *ProductCreate {
	return pc.SetOfficerID(o.ID)
}

// AddProductInsuranceIDs adds the product_insurance edge to Insurance by ids.
func (pc *ProductCreate) AddProductInsuranceIDs(ids ...int) *ProductCreate {
	pc.mutation.AddProductInsuranceIDs(ids...)
	return pc
}

// AddProductInsurance adds the product_insurance edges to Insurance.
func (pc *ProductCreate) AddProductInsurance(i ...*Insurance) *ProductCreate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return pc.AddProductInsuranceIDs(ids...)
}

// Mutation returns the ProductMutation object of the builder.
func (pc *ProductCreate) Mutation() *ProductMutation {
	return pc.mutation
}

// Save creates the Product in the database.
func (pc *ProductCreate) Save(ctx context.Context) (*Product, error) {
	if _, ok := pc.mutation.ProductName(); !ok {
		return nil, &ValidationError{Name: "product_name", err: errors.New("ent: missing required field \"product_name\"")}
	}
	if _, ok := pc.mutation.ProductPrice(); !ok {
		return nil, &ValidationError{Name: "product_price", err: errors.New("ent: missing required field \"product_price\"")}
	}
	if _, ok := pc.mutation.ProductTime(); !ok {
		return nil, &ValidationError{Name: "product_time", err: errors.New("ent: missing required field \"product_time\"")}
	}
	if _, ok := pc.mutation.ProductPaymentOfYear(); !ok {
		return nil, &ValidationError{Name: "product_payment_of_year", err: errors.New("ent: missing required field \"product_payment_of_year\"")}
	}
	var (
		err  error
		node *Product
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ProductCreate) SaveX(ctx context.Context) *Product {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *ProductCreate) sqlSave(ctx context.Context) (*Product, error) {
	pr, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pr.ID = int(id)
	return pr, nil
}

func (pc *ProductCreate) createSpec() (*Product, *sqlgraph.CreateSpec) {
	var (
		pr    = &Product{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: product.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: product.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.ProductName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: product.FieldProductName,
		})
		pr.ProductName = value
	}
	if value, ok := pc.mutation.ProductPrice(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: product.FieldProductPrice,
		})
		pr.ProductPrice = value
	}
	if value, ok := pc.mutation.ProductTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: product.FieldProductTime,
		})
		pr.ProductTime = value
	}
	if value, ok := pc.mutation.ProductPaymentOfYear(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldProductPaymentOfYear,
		})
		pr.ProductPaymentOfYear = value
	}
	if nodes := pc.mutation.GenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   product.GenderTable,
			Columns: []string{product.GenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: gender.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.GoupOfAgeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   product.GoupOfAgeTable,
			Columns: []string{product.GoupOfAgeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: groupofage.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.OfficerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   product.OfficerTable,
			Columns: []string{product.OfficerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: officer.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.ProductInsuranceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.ProductInsuranceTable,
			Columns: []string{product.ProductInsuranceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: insurance.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pr, _spec
}
