// Code generated by entc, DO NOT EDIT.

package recordinsurance

import (
	"time"
)

const (
	// Label holds the string label denoting the recordinsurance type in the database.
	Label = "recordinsurance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRecordinsuranceTime holds the string denoting the recordinsurance_time field in the database.
	FieldRecordinsuranceTime = "recordinsurance_time"

	// EdgeMember holds the string denoting the member edge name in mutations.
	EdgeMember = "Member"
	// EdgeHospital holds the string denoting the hospital edge name in mutations.
	EdgeHospital = "Hospital"
	// EdgeOfficer holds the string denoting the officer edge name in mutations.
	EdgeOfficer = "Officer"
	// EdgeProduct holds the string denoting the product edge name in mutations.
	EdgeProduct = "Product"
	// EdgeAmountpaid holds the string denoting the amountpaid edge name in mutations.
	EdgeAmountpaid = "Amountpaid"

	// Table holds the table name of the recordinsurance in the database.
	Table = "recordinsurances"
	// MemberTable is the table the holds the Member relation/edge.
	MemberTable = "recordinsurances"
	// MemberInverseTable is the table name for the Member entity.
	// It exists in this package in order to avoid circular dependency with the "member" package.
	MemberInverseTable = "members"
	// MemberColumn is the table column denoting the Member relation/edge.
	MemberColumn = "member_id"
	// HospitalTable is the table the holds the Hospital relation/edge.
	HospitalTable = "recordinsurances"
	// HospitalInverseTable is the table name for the Hospital entity.
	// It exists in this package in order to avoid circular dependency with the "hospital" package.
	HospitalInverseTable = "hospitals"
	// HospitalColumn is the table column denoting the Hospital relation/edge.
	HospitalColumn = "hospital_id"
	// OfficerTable is the table the holds the Officer relation/edge.
	OfficerTable = "recordinsurances"
	// OfficerInverseTable is the table name for the Officer entity.
	// It exists in this package in order to avoid circular dependency with the "officer" package.
	OfficerInverseTable = "officers"
	// OfficerColumn is the table column denoting the Officer relation/edge.
	OfficerColumn = "officer_id"
	// ProductTable is the table the holds the Product relation/edge.
	ProductTable = "recordinsurances"
	// ProductInverseTable is the table name for the Product entity.
	// It exists in this package in order to avoid circular dependency with the "product" package.
	ProductInverseTable = "products"
	// ProductColumn is the table column denoting the Product relation/edge.
	ProductColumn = "product_id"
	// AmountpaidTable is the table the holds the Amountpaid relation/edge.
	AmountpaidTable = "recordinsurances"
	// AmountpaidInverseTable is the table name for the Amountpaid entity.
	// It exists in this package in order to avoid circular dependency with the "amountpaid" package.
	AmountpaidInverseTable = "amountpaids"
	// AmountpaidColumn is the table column denoting the Amountpaid relation/edge.
	AmountpaidColumn = "amountpaid_id"
)

// Columns holds all SQL columns for recordinsurance fields.
var Columns = []string{
	FieldID,
	FieldRecordinsuranceTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Recordinsurance type.
var ForeignKeys = []string{
	"amountpaid_id",
	"hospital_id",
	"member_id",
	"officer_id",
	"product_id",
}

var (
	// DefaultRecordinsuranceTime holds the default value on creation for the recordinsurance_time field.
	DefaultRecordinsuranceTime func() time.Time
)
