/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersInquiry
 */
export interface ControllersInquiry {
    /**
     * 
     * @type {number}
     * @memberof ControllersInquiry
     */
    categoryID?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersInquiry
     */
    inquiryMessages?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersInquiry
     */
    inquiryTimeMessages?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersInquiry
     */
    memberID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersInquiry
     */
    officerID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersInquiry
     */
    productID?: number;
}

export function ControllersInquiryFromJSON(json: any): ControllersInquiry {
    return ControllersInquiryFromJSONTyped(json, false);
}

export function ControllersInquiryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersInquiry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categoryID': !exists(json, 'categoryID') ? undefined : json['categoryID'],
        'inquiryMessages': !exists(json, 'inquiryMessages') ? undefined : json['inquiryMessages'],
        'inquiryTimeMessages': !exists(json, 'inquiryTimeMessages') ? undefined : json['inquiryTimeMessages'],
        'memberID': !exists(json, 'memberID') ? undefined : json['memberID'],
        'officerID': !exists(json, 'officerID') ? undefined : json['officerID'],
        'productID': !exists(json, 'productID') ? undefined : json['productID'],
    };
}

export function ControllersInquiryToJSON(value?: ControllersInquiry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categoryID': value.categoryID,
        'inquiryMessages': value.inquiryMessages,
        'inquiryTimeMessages': value.inquiryTimeMessages,
        'memberID': value.memberID,
        'officerID': value.officerID,
        'productID': value.productID,
    };
}


