/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersRecordinsurance
 */
export interface ControllersRecordinsurance {
    /**
     * 
     * @type {number}
     * @memberof ControllersRecordinsurance
     */
    amountpaidID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersRecordinsurance
     */
    hospitalID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersRecordinsurance
     */
    memberID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersRecordinsurance
     */
    numberOfDaysOfTreat?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersRecordinsurance
     */
    officerID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersRecordinsurance
     */
    productID?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersRecordinsurance
     */
    recordinsuranceAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersRecordinsurance
     */
    recordinsuranceContact?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersRecordinsurance
     */
    recordinsuranceTime?: string;
}

export function ControllersRecordinsuranceFromJSON(json: any): ControllersRecordinsurance {
    return ControllersRecordinsuranceFromJSONTyped(json, false);
}

export function ControllersRecordinsuranceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersRecordinsurance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amountpaidID': !exists(json, 'amountpaidID') ? undefined : json['amountpaidID'],
        'hospitalID': !exists(json, 'hospitalID') ? undefined : json['hospitalID'],
        'memberID': !exists(json, 'memberID') ? undefined : json['memberID'],
        'numberOfDaysOfTreat': !exists(json, 'numberOfDaysOfTreat') ? undefined : json['numberOfDaysOfTreat'],
        'officerID': !exists(json, 'officerID') ? undefined : json['officerID'],
        'productID': !exists(json, 'productID') ? undefined : json['productID'],
        'recordinsuranceAddress': !exists(json, 'recordinsuranceAddress') ? undefined : json['recordinsuranceAddress'],
        'recordinsuranceContact': !exists(json, 'recordinsuranceContact') ? undefined : json['recordinsuranceContact'],
        'recordinsuranceTime': !exists(json, 'recordinsuranceTime') ? undefined : json['recordinsuranceTime'],
    };
}

export function ControllersRecordinsuranceToJSON(value?: ControllersRecordinsurance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amountpaidID': value.amountpaidID,
        'hospitalID': value.hospitalID,
        'memberID': value.memberID,
        'numberOfDaysOfTreat': value.numberOfDaysOfTreat,
        'officerID': value.officerID,
        'productID': value.productID,
        'recordinsuranceAddress': value.recordinsuranceAddress,
        'recordinsuranceContact': value.recordinsuranceContact,
        'recordinsuranceTime': value.recordinsuranceTime,
    };
}


