/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersInsurance
 */
export interface ControllersInsurance {
    /**
     * 
     * @type {number}
     * @memberof ControllersInsurance
     */
    hospitalID?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersInsurance
     */
    insuranceAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersInsurance
     */
    insuranceInsurer?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersInsurance
     */
    insuranceTimeBuy?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersInsurance
     */
    insuranceTimeFirstpay?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersInsurance
     */
    memberID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersInsurance
     */
    officerID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersInsurance
     */
    productID?: number;
}

export function ControllersInsuranceFromJSON(json: any): ControllersInsurance {
    return ControllersInsuranceFromJSONTyped(json, false);
}

export function ControllersInsuranceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersInsurance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hospitalID': !exists(json, 'hospitalID') ? undefined : json['hospitalID'],
        'insuranceAddress': !exists(json, 'insuranceAddress') ? undefined : json['insuranceAddress'],
        'insuranceInsurer': !exists(json, 'insuranceInsurer') ? undefined : json['insuranceInsurer'],
        'insuranceTimeBuy': !exists(json, 'insuranceTimeBuy') ? undefined : json['insuranceTimeBuy'],
        'insuranceTimeFirstpay': !exists(json, 'insuranceTimeFirstpay') ? undefined : json['insuranceTimeFirstpay'],
        'memberID': !exists(json, 'memberID') ? undefined : json['memberID'],
        'officerID': !exists(json, 'officerID') ? undefined : json['officerID'],
        'productID': !exists(json, 'productID') ? undefined : json['productID'],
    };
}

export function ControllersInsuranceToJSON(value?: ControllersInsurance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hospitalID': value.hospitalID,
        'insuranceAddress': value.insuranceAddress,
        'insuranceInsurer': value.insuranceInsurer,
        'insuranceTimeBuy': value.insuranceTimeBuy,
        'insuranceTimeFirstpay': value.insuranceTimeFirstpay,
        'memberID': value.memberID,
        'officerID': value.officerID,
        'productID': value.productID,
    };
}


