/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntInsuranceEdges,
    EntInsuranceEdgesFromJSON,
    EntInsuranceEdgesFromJSONTyped,
    EntInsuranceEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntInsurance
 */
export interface EntInsurance {
    /**
     * 
     * @type {EntInsuranceEdges}
     * @memberof EntInsurance
     */
    edges?: EntInsuranceEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntInsurance
     */
    id?: number;
    /**
     * InsuranceAddress holds the value of the "insurance_address" field.
     * @type {string}
     * @memberof EntInsurance
     */
    insuranceAddress?: string;
    /**
     * InsuranceInsurer holds the value of the "insurance_insurer" field.
     * @type {string}
     * @memberof EntInsurance
     */
    insuranceInsurer?: string;
    /**
     * InsuranceTimeBuy holds the value of the "insurance_time_buy" field.
     * @type {string}
     * @memberof EntInsurance
     */
    insuranceTimeBuy?: string;
    /**
     * InsuranceTimeFirstpay holds the value of the "insurance_time_firstpay" field.
     * @type {string}
     * @memberof EntInsurance
     */
    insuranceTimeFirstpay?: string;
}

export function EntInsuranceFromJSON(json: any): EntInsurance {
    return EntInsuranceFromJSONTyped(json, false);
}

export function EntInsuranceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntInsurance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntInsuranceEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'insuranceAddress': !exists(json, 'insurance_address') ? undefined : json['insurance_address'],
        'insuranceInsurer': !exists(json, 'insurance_insurer') ? undefined : json['insurance_insurer'],
        'insuranceTimeBuy': !exists(json, 'insurance_time_buy') ? undefined : json['insurance_time_buy'],
        'insuranceTimeFirstpay': !exists(json, 'insurance_time_firstpay') ? undefined : json['insurance_time_firstpay'],
    };
}

export function EntInsuranceToJSON(value?: EntInsurance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntInsuranceEdgesToJSON(value.edges),
        'id': value.id,
        'insurance_address': value.insuranceAddress,
        'insurance_insurer': value.insuranceInsurer,
        'insurance_time_buy': value.insuranceTimeBuy,
        'insurance_time_firstpay': value.insuranceTimeFirstpay,
    };
}


