/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntInquiryEdges,
    EntInquiryEdgesFromJSON,
    EntInquiryEdgesFromJSONTyped,
    EntInquiryEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntInquiry
 */
export interface EntInquiry {
    /**
     * InquiryMessages holds the value of the "Inquiry_messages" field.
     * @type {string}
     * @memberof EntInquiry
     */
    inquiryMessages?: string;
    /**
     * InquiryTimeMessages holds the value of the "Inquiry_time_messages" field.
     * @type {string}
     * @memberof EntInquiry
     */
    inquiryTimeMessages?: string;
    /**
     * 
     * @type {EntInquiryEdges}
     * @memberof EntInquiry
     */
    edges?: EntInquiryEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntInquiry
     */
    id?: number;
}

export function EntInquiryFromJSON(json: any): EntInquiry {
    return EntInquiryFromJSONTyped(json, false);
}

export function EntInquiryFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntInquiry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inquiryMessages': !exists(json, 'Inquiry_messages') ? undefined : json['Inquiry_messages'],
        'inquiryTimeMessages': !exists(json, 'Inquiry_time_messages') ? undefined : json['Inquiry_time_messages'],
        'edges': !exists(json, 'edges') ? undefined : EntInquiryEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntInquiryToJSON(value?: EntInquiry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Inquiry_messages': value.inquiryMessages,
        'Inquiry_time_messages': value.inquiryTimeMessages,
        'edges': EntInquiryEdgesToJSON(value.edges),
        'id': value.id,
    };
}


