/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntMemberEdges,
    EntMemberEdgesFromJSON,
    EntMemberEdgesFromJSONTyped,
    EntMemberEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntMember
 */
export interface EntMember {
    /**
     * 
     * @type {EntMemberEdges}
     * @memberof EntMember
     */
    edges?: EntMemberEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntMember
     */
    id?: number;
    /**
     * MemberEmail holds the value of the "member_email" field.
     * @type {string}
     * @memberof EntMember
     */
    memberEmail?: string;
    /**
     * MemberName holds the value of the "member_name" field.
     * @type {string}
     * @memberof EntMember
     */
    memberName?: string;
    /**
     * MemberPassword holds the value of the "member_password" field.
     * @type {string}
     * @memberof EntMember
     */
    memberPassword?: string;
}

export function EntMemberFromJSON(json: any): EntMember {
    return EntMemberFromJSONTyped(json, false);
}

export function EntMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntMember {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntMemberEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'memberEmail': !exists(json, 'member_email') ? undefined : json['member_email'],
        'memberName': !exists(json, 'member_name') ? undefined : json['member_name'],
        'memberPassword': !exists(json, 'member_password') ? undefined : json['member_password'],
    };
}

export function EntMemberToJSON(value?: EntMember | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntMemberEdgesToJSON(value.edges),
        'id': value.id,
        'member_email': value.memberEmail,
        'member_name': value.memberName,
        'member_password': value.memberPassword,
    };
}


