/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBank,
    EntBankFromJSON,
    EntBankFromJSONTyped,
    EntBankToJSON,
    EntMember,
    EntMemberFromJSON,
    EntMemberFromJSONTyped,
    EntMemberToJSON,
    EntOfficer,
    EntOfficerFromJSON,
    EntOfficerFromJSONTyped,
    EntOfficerToJSON,
    EntProduct,
    EntProductFromJSON,
    EntProductFromJSONTyped,
    EntProductToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPaybackEdges
 */
export interface EntPaybackEdges {
    /**
     * 
     * @type {EntBank}
     * @memberof EntPaybackEdges
     */
    bank?: EntBank;
    /**
     * 
     * @type {EntMember}
     * @memberof EntPaybackEdges
     */
    member?: EntMember;
    /**
     * 
     * @type {EntOfficer}
     * @memberof EntPaybackEdges
     */
    officer?: EntOfficer;
    /**
     * 
     * @type {EntProduct}
     * @memberof EntPaybackEdges
     */
    product?: EntProduct;
}

export function EntPaybackEdgesFromJSON(json: any): EntPaybackEdges {
    return EntPaybackEdgesFromJSONTyped(json, false);
}

export function EntPaybackEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPaybackEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bank': !exists(json, 'bank') ? undefined : EntBankFromJSON(json['bank']),
        'member': !exists(json, 'member') ? undefined : EntMemberFromJSON(json['member']),
        'officer': !exists(json, 'officer') ? undefined : EntOfficerFromJSON(json['officer']),
        'product': !exists(json, 'product') ? undefined : EntProductFromJSON(json['product']),
    };
}

export function EntPaybackEdgesToJSON(value?: EntPaybackEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bank': EntBankToJSON(value.bank),
        'member': EntMemberToJSON(value.member),
        'officer': EntOfficerToJSON(value.officer),
        'product': EntProductToJSON(value.product),
    };
}


