/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPaybackEdges,
    EntPaybackEdgesFromJSON,
    EntPaybackEdgesFromJSONTyped,
    EntPaybackEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPayback
 */
export interface EntPayback {
    /**
     * Accountnumber holds the value of the "Accountnumber" field.
     * @type {string}
     * @memberof EntPayback
     */
    accountnumber?: string;
    /**
     * Transfertime holds the value of the "Transfertime" field.
     * @type {string}
     * @memberof EntPayback
     */
    transfertime?: string;
    /**
     * 
     * @type {EntPaybackEdges}
     * @memberof EntPayback
     */
    edges?: EntPaybackEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPayback
     */
    id?: number;
}

export function EntPaybackFromJSON(json: any): EntPayback {
    return EntPaybackFromJSONTyped(json, false);
}

export function EntPaybackFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPayback {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountnumber': !exists(json, 'Accountnumber') ? undefined : json['Accountnumber'],
        'transfertime': !exists(json, 'Transfertime') ? undefined : json['Transfertime'],
        'edges': !exists(json, 'edges') ? undefined : EntPaybackEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntPaybackToJSON(value?: EntPayback | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Accountnumber': value.accountnumber,
        'Transfertime': value.transfertime,
        'edges': EntPaybackEdgesToJSON(value.edges),
        'id': value.id,
    };
}


