// Code generated by entc, DO NOT EDIT.

package moneytransfer

const (
	// Label holds the string label denoting the moneytransfer type in the database.
	Label = "money_transfer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMoneytransferType holds the string denoting the moneytransfer_type field in the database.
	FieldMoneytransferType = "moneytransfer_type"

	// EdgeMoneytransferPayment holds the string denoting the moneytransfer_payment edge name in mutations.
	EdgeMoneytransferPayment = "moneytransfer_payment"

	// Table holds the table name of the moneytransfer in the database.
	Table = "money_transfers"
	// MoneytransferPaymentTable is the table the holds the moneytransfer_payment relation/edge.
	MoneytransferPaymentTable = "payments"
	// MoneytransferPaymentInverseTable is the table name for the Payment entity.
	// It exists in this package in order to avoid circular dependency with the "payment" package.
	MoneytransferPaymentInverseTable = "payments"
	// MoneytransferPaymentColumn is the table column denoting the moneytransfer_payment relation/edge.
	MoneytransferPaymentColumn = "moneytransfer_id"
)

// Columns holds all SQL columns for moneytransfer fields.
var Columns = []string{
	FieldID,
	FieldMoneytransferType,
}

var (
	// MoneytransferTypeValidator is a validator for the "moneytransfer_type" field. It is called by the builders before save.
	MoneytransferTypeValidator func(string) error
)
